import { Entity, PrimaryColumn, Column, ManyToOne, JoinColumn } from 'typeorm'

import { User } from './user'

@Entity('Token')
export class Token {
  @PrimaryColumn() // This is a UUID generated by the app not an integer generated by the DB.
  id!: string

  @Column({ type: 'time', default: () => new Date().getTime() })
  createdAt: string

  @Column({ type: 'time', default: () => new Date().getTime() })
  updatedAt: string

  @Column()
  hashedToken: string

  @Column({ type: 'time' })
  expiresAt: string

  @ManyToOne((type) => User)
  @JoinColumn({ name: 'id' })
  user: User
}
